base_directories = [
    ("Product Hunt", "https://www.producthunt.com/posts/new"),
    ("Hacker News (Show HN)", "https://news.ycombinator.com/submit"),
    ("Indie Hackers", "https://www.indiehackers.com/products/new"),
    ("AlternativeTo", "https://alternativeto.net/software/add/"),
    ("G2", "https://www.g2.com/products/new"),
    ("Capterra", "https://www.capterra.com/vendors/new"),
    ("Trustpilot", "https://business.trustpilot.com/"),
    ("Crunchbase", "https://www.crunchbase.com/add-new"),
    ("Wellfound (AngelList)", "https://wellfound.com/companies/new"),
    ("Dev.to", "https://dev.to/new"),
    ("Betalist", "https://betalist.com/submit"),
    ("SaaSHub", "https://www.saashub.com/submit"),
    ("StartupStash", "https://startupstash.com/add-listing/"),
    ("There's An AI For That", "https://theresanaiforthat.com/submit/"),
    ("Futurepedia", "https://www.futurepedia.io/submit-tool"),
    ("AI Tool Hunt", "https://www.aitoolhunt.com/submit"),
    ("Toolify.ai", "https://www.toolify.ai/submit"),
    ("Starter Story", "https://www.starterstory.com/join"),
    ("StackShare", "https://stackshare.io/tools/new"),
    ("Slant", "https://www.slant.co/topics/new"),
    ("AppSumo", "https://sell.appsumo.com/"),
    ("Uneed", "https://www.uneed.best/submit"),
    ("Peerlist", "https://peerlist.io/projects/new"),
    ("Microlaunch", "https://microlaunch.net/submit"),
    ("1000 Tools", "https://1000.tools/submit"),
    ("F6S", "https://www.f6s.com/"),
    ("Software Advice", "https://www.softwareadvice.com/vendors/"),
    ("GetApp", "https://www.getapp.com/vendors/"),
    ("TrustRadius", "https://www.trustradius.com/vendor"),
    ("SaaSWorthy", "https://www.saasworthy.com/add-product"),
    ("SourceForge", "https://sourceforge.net/create/"),
    ("GoodFirms", "https://www.goodfirms.co/add-company"),
    ("Clutch", "https://clutch.co/get-listed"),
    ("BetaPage", "https://betapage.co/submit"),
    ("Launching Next", "https://www.launchingnext.com/submit/"),
    ("StartupBuffer", "https://startupbuffer.com/submit"),
    ("Hashnode", "https://hashnode.com/draft"),
    ("TechCrunch (Pitch)", "https://techcrunch.com/pages/pitch/"),
    ("Makerlog", "https://getmakerlog.com/"),
    ("WIP.co", "https://wip.co/"),
    ("PitchWall", "https://pitchwall.co/submit"),
    ("CrazyAboutStartups", "https://crazyaboutstartups.com/submit-startup/"),
    ("AI Valley", "https://aivalley.ai/submit-tool/"),
    ("TopAI.tools", "https://topai.tools/submit"),
    ("GPT Store", "https://chatgpt.com/gpts"),
    ("AiTools.fyi", "https://aitools.fyi/submit"),
    ("Tools.so", "https://tools.so/submit"),
    ("StartupBase", "https://startupbase.io/submit"),
    ("Startups.fyi", "https://www.startups.fyi/submit"),
    ("Reddit r/SaaS", "https://www.reddit.com/r/SaaS/submit"),
    ("Reddit r/SideProject", "https://www.reddit.com/r/SideProject/submit"),
    ("Reddit r/Entrepreneur", "https://www.reddit.com/r/Entrepreneur/submit"),
    ("Reddit r/Startups", "https://www.reddit.com/r/startups/submit")
]

TARGET_DIRECTORIES = base_directories.copy()
